on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shield:
          - porcupine_mac_left
          - porcupine_mac_right
          - porcupine_win_left
          - porcupine_win_right
          - settings_reset
    name: Build for ${{ matrix.shield }}
    steps:
      - uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
        with:
          board: nice_nano_v2
          shield: ${{ matrix.shield }}
